name: Build and Update Hash
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-hash:
    name: Update Nix Hash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Extract current hash
        id: current-hash
        run: |
          CURRENT_HASH=$(grep 'cargoSha256 = ' flake.nix | sed 's/.*"\(.*\)".*/\1/' | xargs)
          echo "hash=$CURRENT_HASH" >> $GITHUB_OUTPUT

      - name: Get new hash
        id: new-hash
        run: |
          # Temporarily replace the hash with a fake one
          sed -i 's/cargoSha256 = ".*"/cargoSha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="/' flake.nix
          
          # Try to build and capture the error message containing the correct hash
          NEW_HASH=$(nix build 2>&1 | grep 'got:' | sed 's/.*got: \(.*\)/\1/' | xargs)
          echo "hash=$NEW_HASH" >> $GITHUB_OUTPUT

      - name: Update hash if different
        if: steps.current-hash.outputs.hash != steps.new-hash.outputs.hash
        run: |
          # Create the new line with proper formatting
          NEW_LINE="            cargoSha256 = \"${{ steps.new-hash.outputs.hash }}\";"
          
          # Use perl for more precise replacement
          perl -i -pe 's/\s*cargoSha256 = ".*";/$ENV{NEW_LINE}/' flake.nix
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add flake.nix
          git commit -m "chore: update cargoSha256 hash"
          git push